# Generated by Django 2.2.16 on 2020-10-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='Company',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
